version: '3.3'

services:
  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - rotten_net
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
    
  mongodb:
    image: mongo:4.4.3
    restart: always
    ports:
      - 27017:27017
    networks:
      - rotten_net
    volumes:
      - rotten_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_INITDB_DATABASE: admin

  mongoexpress:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    networks:
      - rotten_net
    links:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd

networks:
  rotten_net:
    driver: bridge

volumes:
  rotten_vol: